print("You will be adding or subtracting 2 numbers together!")
number_1 = (input("Select a number:"))
number_2 = (input("Select another number:"))
answer = int(number_1) + int(number_2)
print(f"Your answer is {answer}!")

print("you will be multiplying 2 numbers together!")
number_1 = (input("Select a number:"))
number_2 = (input("Select another number:"))
answer = int(number_1) * int(number_2)
print(f"Your answer is {answer}!")